version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    ports:
     - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: 'fcco'
      MYSQL_DATABASE: 'fcco'
      
    volumes:
      - ./db:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3031:80
    environment:  
      PMA_HOST: mysql  

  drupal:
    image: drupal:8.6.1
    ports:
      - 3030:80
    volumes:
     - ./modules:/var/www/html/modules
     - ./profiles:/var/www/html/profiles
     - ./themes:/var/www/html/themes
     # this takes advantage of the feature in Docker that a new anonymous
     # volume (which is what we're creating here) will be initialized with the
     # existing content of the image at the same location
     #- ./sites:/var/www/html/sites
    restart: always